apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: lcow-injector-cfg
  labels:
    app: lcow-injector
  namespace: injector
webhooks:
  - name: lcow-injector.sachinmsft.me
    failurePolicy: Fail
    clientConfig:
      service:
        name: lcow-injector-webhook-svc
        namespace: injector
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
          - injector
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods","deployments","replicasets","statefulsets"]
