# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Kube-Proxy images

on:
  workflow_dispatch:
    inputs:
      proxy_version:
        description: 'Version of kube-proxy to build (ex: v1.27.1)'
        required: true
      repository:
        description: 'Repository to push the image to (ex: docker.io/sigwindowstools)'
        required: false
        default: 'docker.io/sigwindowstools'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Login to DockerHub
      if: startsWith(github.event.inputs.repository, 'docker.io')
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Build and push images
      run: |
        pushd ./hostprocess/calico
        ./build.sh -p ${{ github.event.inputs.proxy_version }} -r ${{ github.event.inputs.repository }}
