name: copy-image

on:
  workflow_dispatch:
    inputs:
      imageAndVersion:
        required: true
        description: 'image name and tag for images - must be present in hub.docker.com/u/sigwindowstools!'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: copy image
        run: |
          curl -L https://github.com/regclient/regclient/releases/download/v0.4.1/regctl-linux-amd64 -o regctl
          chmod +x regctl
          ./regctl version
          ./regctl image copy -v=info sigwindowstools/${{ github.event.inputs.imageAndVersion}} ghcr.io/$GITHUB_REPOSITORY_OWNER/sig-windows/${{ github.event.inputs.imageAndVersion }}
