name: sync-registries

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: copy image
        run: |
          curl -L https://github.com/regclient/regclient/releases/download/v0.4.2/regsync-linux-amd64 -o regsync
          chmod +x regsync
          ./regsync version
          ./regsync once -c hack/regsync.yaml
