name: sync-registries

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: copy image
        run: |
          curl -L https://github.com/regclient/regclient/releases/download/v0.4.2/regsync-linux-amd64 -o regsync
          chmod +x regsync
          ./regsync version
          ./regsync once -c hack/regsync.yaml
