# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: test-kube-proxy-images

on:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    name: Run script
    runs-on: windows-latest

    steps:
    - name: dockerhub login
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Test kube-proxy images
      run: powershell.exe ./hack/test-kube-proxy-images.ps1
